export type SportradarAPI_MLB_V7_GameStatus = "scheduled"
	| "inprogress"
	| "complete"
	| "closed"
	| "canceled"
	| "postponed"
	| "suspended"
	| "wdelay"
	| "fdelay"
	| "odelay"
	| "maintenance"
	| "unnecessary"
